.LOGTABLE vmtest.logtable;

.logon 127.0.0.1/dbc, dbc;

   .BEGIN MLOAD TABLES vmtest.ACCOUNT_DETAIL_PERIODIC;
      .LAYOUT Data;  
		.FIELD in_WH_ACC_NO * VARCHAR(30);
		.FIELD in_ACC_NO * VARCHAR(16) ;
		.FIELD in_GL_CORPTN * VARCHAR(5) ;
		.FIELD in_ISO_CNTRY_CDE * VARCHAR(2) ;
		.FIELD in_ISO_CRNCY_CDE * VARCHAR(3) ;
		.FIELD in_CLOSE_DTE * VARCHAR(20) ;
		.FIELD in_BAL_AMT * VARCHAR(30);
		.FIELD in_NET_BAL_FOR_PRNCPL * VARCHAR(30);
		.FIELD in_BAL_FOR_INT * VARCHAR(30);
		.FIELD in_LIMIT_AMT * VARCHAR(30);
		.FIELD in_MARGIN_REF_RTE * VARCHAR(30);
		.FIELD in_ACCRD_INT * VARCHAR(30);
		.FIELD in_CNTRACT_MATURITY_DTE * VARCHAR(20) ;
		.FIELD in_CONTRACT_EFF_DTE * VARCHAR(20) ;
		.FIELD in_ACC_SETUP_DTE * VARCHAR(20) ;
		.FIELD in_FIRST_TRANS_DTE * VARCHAR(20) ;
		.FIELD in_LAST_DR_DTE * VARCHAR(20) ;
		.FIELD in_LAST_CR_DTE * VARCHAR(20) ;
		.FIELD in_BOE_SECTOR_CDE * VARCHAR(20) ;
		.FIELD in_CR_GRADE * VARCHAR(1) ;
		.FIELD in_RESTRICTED_ACCESS_IND * VARCHAR(1) ;
		.FIELD in_SUB_ORG_CDE * VARCHAR(10) ;
		.FIELD in_SRCE_PROD_CDE * VARCHAR(20) ;
		.FIELD in_PROD_CDE * VARCHAR(30);
		.FIELD in_INT_RTE * VARCHAR(30);
		.FIELD in_NET_LIMIT_FOR_PRNCPL * VARCHAR(30);
		.FIELD in_SRCE_CR_GRADE * VARCHAR(1) ;
		.FIELD in_SRCE_BRANCH_NO * VARCHAR(5) ;
		.FIELD in_IBAN_NO * VARCHAR(28) ;
		.FIELD in_STA_CDE * VARCHAR(1) ;
		.FIELD in_SRCE_STA_CDE * VARCHAR(16) ;
		.FIELD in_LAST_MAINTAINED_DTE * VARCHAR(20) ;
		.FIELD in_LAST_CUST_TRANS_DTE * VARCHAR(20) ;
		.FIELD in_WH_CHNL_ID * VARCHAR(30) ;
		.FIELD in_WH_ORG_UNIT_ID * VARCHAR(30) ;
		.FIELD in_CONTRACT_BEG_DTE * VARCHAR(20) ;
		.FIELD in_MIGRATION_CDE * VARCHAR(1) ;
		.FIELD in_DCRG_LMT_IND * VARCHAR(1) ;
		.FIELD in_PERIOD_DTE * VARCHAR(20) ;
		.FIELD in_SRCE_SYS * VARCHAR(20) ;
		.FIELD in_SRCE_INST * VARCHAR(20) ;
		.FIELD in_LOAD_LAST_ACTION * VARCHAR(1) ;
		.FIELD in_LOAD_DTE * VARCHAR(20) ;
		.FIELD in_LOAD_TIME * VARCHAR(30) ;

      .DML LABEL DataLabel;
      INSERT INTO vmtest.ACCOUNT_DETAIL_PERIODIC
      VALUES (
		:in_WH_ACC_NO ,
		:in_ACC_NO ,
		:in_GL_CORPTN ,
		:in_ISO_CNTRY_CDE ,
		:in_ISO_CRNCY_CDE ,
		:in_CLOSE_DTE ,
		:in_BAL_AMT ,
		:in_NET_BAL_FOR_PRNCPL ,
		:in_BAL_FOR_INT ,
		:in_LIMIT_AMT ,
		:in_MARGIN_REF_RTE ,
		:in_ACCRD_INT ,
		:in_CNTRACT_MATURITY_DTE ,
		:in_CONTRACT_EFF_DTE ,
		:in_ACC_SETUP_DTE ,
		:in_FIRST_TRANS_DTE ,
		:in_LAST_DR_DTE ,
		:in_LAST_CR_DTE ,
		:in_BOE_SECTOR_CDE ,
		:in_CR_GRADE ,
		:in_RESTRICTED_ACCESS_IND ,
		:in_SUB_ORG_CDE ,
		:in_SRCE_PROD_CDE ,
		:in_PROD_CDE ,
		:in_INT_RTE ,
		:in_NET_LIMIT_FOR_PRNCPL ,
		:in_SRCE_CR_GRADE ,
		:in_SRCE_BRANCH_NO ,
		:in_IBAN_NO ,
		:in_STA_CDE ,
		:in_SRCE_STA_CDE ,
		:in_LAST_MAINTAINED_DTE ,
		:in_LAST_CUST_TRANS_DTE ,
		:in_WH_CHNL_ID ,
		:in_WH_ORG_UNIT_ID ,
		:in_CONTRACT_BEG_DTE ,
		:in_MIGRATION_CDE ,
		:in_DCRG_LMT_IND ,
		:in_PERIOD_DTE ,
		:in_SRCE_SYS ,
		:in_SRCE_INST ,
		:in_LOAD_LAST_ACTION ,
		:in_LOAD_DTE ,
		:in_LOAD_TIME
      );
      .IMPORT INFILE ../dane_testowe/ACCOUNT_DETAIL_PERIODIC_DATA_FILE.dat
      FORMAT VARTEXT ''
      LAYOUT Data
      APPLY DataLabel;  
   .END MLOAD;  
LOGOFF;

