.LOGTABLE vmtest.logtable;

.logon 127.0.0.1/dbc, dbc;

   .BEGIN MLOAD TABLES vmtest.CUSTOMER_STATIC_HISTORY;
      .LAYOUT Data;
		.FIELD in_WH_CUST_NO * VARCHAR(20) ;
		.FIELD in_START_DTE * VARCHAR(20) ;
		.FIELD in_END_DTE * VARCHAR(20) ;
		.FIELD in_SUBSIDIARY_ID * VARCHAR(20) ;
		.FIELD in_SRCE_INST * VARCHAR(20) ;
		.FIELD in_SRCE_CUST_NO * VARCHAR(19) ;
		.FIELD in_FULL_NAME * VARCHAR(80) ;
		.FIELD in_RELATIONSHIP_TYPE_CDE * VARCHAR(1) ;
		.FIELD in_MKT_SEG_CDE * VARCHAR(4) ;
		.FIELD in_RESTRICTED_ACCESS_CDE * VARCHAR(1) ;
		.FIELD in_CR_GRADE_CDE * VARCHAR(1) ;
		.FIELD in_BAD_DEBT_DTE * VARCHAR(20) ;
		.FIELD in_CORP_RETAIL_CLS_CDE * VARCHAR(1) ;
		.FIELD in_BUS_SRCE_CDE * VARCHAR(20);
		.FIELD in_SINCE_DTE * VARCHAR(20) ;
		.FIELD in_CONT_PERSON * VARCHAR(20) ;
		.FIELD in_CONT_PH_AREA * VARCHAR(20);
		.FIELD in_CONT_PH_NO * VARCHAR(20);
		.FIELD in_SALUTATION * VARCHAR(20) ;
		.FIELD in_STAFF_CDE * VARCHAR(10) ;
		.FIELD in_HOME_PH_AREA * VARCHAR(20);
		.FIELD in_HOME_PH_NO * VARCHAR(20);
		.FIELD in_BUS_PH_AREA * VARCHAR(20);
		.FIELD in_BUS_PH_NO * VARCHAR(20);
		.FIELD in_STATUS_CDE * VARCHAR(1) ;
		.FIELD in_LAST_VERIFICATION_DTE * VARCHAR(20) ;
		.FIELD in_LAST_MAINTAINED_DTE * VARCHAR(20) ;
		.FIELD in_NO_MAIL_FLG * VARCHAR(1) ;
		.FIELD in_SECTOR_RPT * VARCHAR(1) ;
		.FIELD in_PRIME_WH_ORG_UNIT_ID * VARCHAR(20) ;
		.FIELD in_PRIME_BUS_UNIT_CDE * VARCHAR(20) ;
		.FIELD in_PRIME_BUS_UNIT_START_DTE * VARCHAR(20) ;
		.FIELD in_PRIME_ACC_NO * VARCHAR(16) ;
		.FIELD in_PRIME_SUB_OFFICE_ACC_NO * VARCHAR(20) ;
		.FIELD in_PRIME_TYPE_CDE * VARCHAR(1) ;
		.FIELD in_PRIME_REFERRAL_CDE * VARCHAR(1) ;
		.FIELD in_CIF_OPEN_ACC_COUNT * VARCHAR(20) ;
		.FIELD in_CIF_OPEN_PRIME_BR_ACC_COUNT * VARCHAR(20) ;
		.FIELD in_CIF_BR_DEP_HELD_FLG * VARCHAR(1) ;
		.FIELD in_CIF_CURR_ACC_HELD_FLG * VARCHAR(1) ;
		.FIELD in_CIF_LOAN_HELD_FLG * VARCHAR(1) ;
		.FIELD in_CIF_FINANCE_LEASE_HELD_FLG * VARCHAR(1) ;
		.FIELD in_CIF_CR_CARD_HELD_FLG * VARCHAR(1) ;
		.FIELD in_CIF_ARK_LIFE_HELD_FLG * VARCHAR(1) ;
		.FIELD in_CIF_HOME_LOAN_HELD_FLG * VARCHAR(1) ;
		.FIELD in_CIF_RDC_HELD_FLG * VARCHAR(1) ;
		.FIELD in_CIF_OTH_HELD_FLG * VARCHAR(1) ;
		.FIELD in_CIF_INS_HELD_FLG * VARCHAR(1) ;
		.FIELD in_WH_OPEN_DTE * VARCHAR(20) ;
		.FIELD in_MKT_SUB_SEG_CDE * VARCHAR(4) ;
		.FIELD in_E_SERV_CONSENT_IND * VARCHAR(1) ;
		.FIELD in_E_SERV_CONSENT_DTE * VARCHAR(20) ;
		.FIELD in_E_CUST_CONT_ID * VARCHAR(50) ;
		.FIELD in_CONTACT_TYP_SELECTION_DTE * VARCHAR(20) ;
		.FIELD in_CONT_FORM_CDE * VARCHAR(1) ;
		.FIELD in_SRCE_KB_CUST_NO * VARCHAR(20) ;
		.FIELD in_MIGRATION_CDE * VARCHAR(1) ;
		.FIELD in_MIGRATION_DTE * VARCHAR(20) ;
		.FIELD in_LOAD_LAST_ACTION * VARCHAR(1) ;
		.FIELD in_LOAD_DTE * VARCHAR(20) ;
		.FIELD in_LOAD_TIME * VARCHAR(20) ;

      .DML LABEL DataLabel;
      INSERT INTO vmtest.CUSTOMER_STATIC_HISTORY
      VALUES (
		:in_WH_CUST_NO,
		:in_START_DTE,
		:in_END_DTE,
		:in_SUBSIDIARY_ID,
		:in_SRCE_INST,
		:in_SRCE_CUST_NO,
		:in_FULL_NAME,
		:in_RELATIONSHIP_TYPE_CDE,
		:in_MKT_SEG_CDE,
		:in_RESTRICTED_ACCESS_CDE,
		:in_CR_GRADE_CDE,
		:in_BAD_DEBT_DTE,
		:in_CORP_RETAIL_CLS_CDE,
		:in_BUS_SRCE_CDE,
		:in_SINCE_DTE,
		:in_CONT_PERSON,
		:in_CONT_PH_AREA,
		:in_CONT_PH_NO,
		:in_SALUTATION,
		:in_STAFF_CDE,
		:in_HOME_PH_AREA,
		:in_HOME_PH_NO,
		:in_BUS_PH_AREA,
		:in_BUS_PH_NO,
		:in_STATUS_CDE,
		:in_LAST_VERIFICATION_DTE,
		:in_LAST_MAINTAINED_DTE,
		:in_NO_MAIL_FLG,
		:in_SECTOR_RPT,
		:in_PRIME_WH_ORG_UNIT_ID,
		:in_PRIME_BUS_UNIT_CDE,
		:in_PRIME_BUS_UNIT_START_DTE,
		:in_PRIME_ACC_NO,
		:in_PRIME_SUB_OFFICE_ACC_NO,
		:in_PRIME_TYPE_CDE,
		:in_PRIME_REFERRAL_CDE,
		:in_CIF_OPEN_ACC_COUNT,
		:in_CIF_OPEN_PRIME_BR_ACC_COUNT,
		:in_CIF_BR_DEP_HELD_FLG,
		:in_CIF_CURR_ACC_HELD_FLG,
		:in_CIF_LOAN_HELD_FLG,
		:in_CIF_FINANCE_LEASE_HELD_FLG,
		:in_CIF_CR_CARD_HELD_FLG,
		:in_CIF_ARK_LIFE_HELD_FLG,
		:in_CIF_HOME_LOAN_HELD_FLG,
		:in_CIF_RDC_HELD_FLG,
		:in_CIF_OTH_HELD_FLG,
		:in_CIF_INS_HELD_FLG,
		:in_WH_OPEN_DTE,
		:in_MKT_SUB_SEG_CDE,
		:in_E_SERV_CONSENT_IND,
		:in_E_SERV_CONSENT_DTE,
		:in_E_CUST_CONT_ID,
		:in_CONTACT_TYP_SELECTION_DTE,
		:in_CONT_FORM_CDE,
		:in_SRCE_KB_CUST_NO,
		:in_MIGRATION_CDE,
		:in_MIGRATION_DTE,
		:in_LOAD_LAST_ACTION,
		:in_LOAD_DTE,
		:in_LOAD_TIME
      );
      .IMPORT INFILE ../dane_testowe/CUSTOMER_STATIC_HISTORY_DATA_FILE.dat
      FORMAT VARTEXT ''
      LAYOUT Data
      APPLY DataLabel;  
   .END MLOAD;  
LOGOFF;

