.LOGTABLE vmtest.logtable;

.logon 127.0.0.1/dbc, dbc;

   .BEGIN MLOAD TABLES vmtest.CUSTOMER_PERSONAL_DETAIL2;
      .LAYOUT Data;
		.FIELD in_WH_CUST_NO * VARCHAR(20) ;
		.FIELD in_SUBSIDIARY_ID * VARCHAR(20) ;
		.FIELD in_SRCE_INST * VARCHAR(20) ;
		.FIELD in_SRCE_CUST_NO * VARCHAR(19) ;
		.FIELD in_CRNCY_CDE * VARCHAR(3) ;
		.FIELD in_OCCUP_TYPE_CDE * VARCHAR(20);
		.FIELD in_LAST_NAME * VARCHAR(60) ;
		.FIELD in_FIRST_NAME * VARCHAR(30) ;
		.FIELD in_MIDDLE_INIT * VARCHAR(1) ;
		.FIELD in_SFX * VARCHAR(2) ;
		.FIELD in_CUST_TITLE * VARCHAR(20) ;
		.FIELD in_EMPLOYMENT_GRP_CDE * VARCHAR(3) ;
		.FIELD in_MARITAL_STA * VARCHAR(1) ;
		.FIELD in_SEX_CDE * VARCHAR(1) ;
		.FIELD in_DOB * VARCHAR(20) ;
		.FIELD in_EMPLR_NAME * VARCHAR(100) ;
		.FIELD in_EMPLR_OCCUP_CDE * VARCHAR(5) ;
		.FIELD in_EMPLOYMENT_NARR * VARCHAR(20) ;
		.FIELD in_EMPLOYMENT_DTE * VARCHAR(20) ;
		.FIELD in_EMPLOYMENT_STA_CDE * VARCHAR(3) ;
		.FIELD in_EMPL_CLS_EMPL * VARCHAR(1) ;
		.FIELD in_EMPL_CLS_SELF * VARCHAR(1) ;
		.FIELD in_EMPL_CLS_HOUSEWIFE * VARCHAR(1) ;
		.FIELD in_EMPL_CLS_STUDENT * VARCHAR(1) ;
		.FIELD in_EMPL_CLS_RETIRED * VARCHAR(1) ;
		.FIELD in_EMPL_CLS_UNEMPLOYED * VARCHAR(1) ;
		.FIELD in_EMPL_TYPE_PERM * VARCHAR(1) ;
		.FIELD in_EMPL_TYPE_PART_TIME * VARCHAR(1) ;
		.FIELD in_EMPL_TYPE_TEMP * VARCHAR(1) ;
		.FIELD in_EMPL_TYPE_PENSION * VARCHAR(1) ;
		.FIELD in_EMPL_TYPE_FULL_TIME * VARCHAR(1) ;
		.FIELD in_SALARY_EFF_DTE * VARCHAR(20) ;
		.FIELD in_INC_AMT * VARCHAR(20);
		.FIELD in_INC_REF_CRNCY_AMT * VARCHAR(20);
		.FIELD in_INC_RANGE * VARCHAR(1) ;
		.FIELD in_PAY_DIR * VARCHAR(1) ;
		.FIELD in_NET_MONTHLY_PAY * VARCHAR(20);
		.FIELD in_NET_MONTHLY_REF_CRNCY_PAY * VARCHAR(20);
		.FIELD in_PAY_FREQ * VARCHAR(1) ;
		.FIELD in_FAMILY_TOTAL_NO * VARCHAR(20) ;
		.FIELD in_FAMILY_FROM_DTE * VARCHAR(20) ;
		.FIELD in_FAMILY_TO_DTE * VARCHAR(20) ;
		.FIELD in_HOUSE_STA_CDE * VARCHAR(1) ;
		.FIELD in_HOUSE_VALUE * VARCHAR(20);
		.FIELD in_HOUSE_REF_CRNCY_VALUE * VARCHAR(20);
		.FIELD in_HOUSE_VALUE_DTE * VARCHAR(20) ;
		.FIELD in_DECEASED_FLG * VARCHAR(1) ;
		.FIELD in_PERSONAL_RSI * VARCHAR(11) ;
		.FIELD in_PART_TIME_HOURS * VARCHAR(20) ;
		.FIELD in_STUDENT_CAT_CDE * VARCHAR(3) ;
		.FIELD in_PRIM_SCH_NAME * VARCHAR(30) ;
		.FIELD in_PRIM_END_DTE * VARCHAR(20) ;
		.FIELD in_SECNDRY_SCH_NAME * VARCHAR(30) ;
		.FIELD in_SECNDRY_END_DTE * VARCHAR(20) ;
		.FIELD in_TRD_LEV_CDE * VARCHAR(3) ;
		.FIELD in_CRSE_TYP_CDE * VARCHAR(3) ;
		.FIELD in_FAC_CDE * VARCHAR(3) ;
		.FIELD in_CRSE_TITLE * VARCHAR(40) ;
		.FIELD in_CRSE_START_DTE * VARCHAR(20) ;
		.FIELD in_CRSE_END_DTE * VARCHAR(20) ;
		.FIELD in_AMEND_RSN_CDE * VARCHAR(3) ;
		.FIELD in_LAST_STAFF_CDE * VARCHAR(20);
		.FIELD in_LAST_UPD_STUDENT_DTE * VARCHAR(20) ;
		.FIELD in_LAST_UPD_STUDENT_TIME * VARCHAR(20) ;
		.FIELD in_WH_OPEN_DTE * VARCHAR(20) ;
		.FIELD in_MONTHLY_NET_INCOME_VERFD_AMT * VARCHAR(20);
		.FIELD in_MONTHLY_NET_INCOME_VERFD_DTE * VARCHAR(20) ;
		.FIELD in_MONTHLY_NET_INCOME_VERFD_TYP * VARCHAR(2) ;
		.FIELD in_PROFESSION_TYPE_CDE * VARCHAR(20);
		.FIELD in_LOAD_LAST_ACTION * VARCHAR(1) ;
		.FIELD in_LOAD_DTE * VARCHAR(20) ;
		.FIELD in_LOAD_TIME * VARCHAR(20) ;

      .DML LABEL DataLabel;
      INSERT INTO vmtest.CUSTOMER_PERSONAL_DETAIL2
      VALUES (
		:in_WH_CUST_NO,
		:in_SUBSIDIARY_ID,
		:in_SRCE_INST,
		:in_SRCE_CUST_NO,
		:in_CRNCY_CDE,
		:in_OCCUP_TYPE_CDE,
		:in_LAST_NAME,
		:in_FIRST_NAME,
		:in_MIDDLE_INIT,
		:in_SFX,
		:in_CUST_TITLE,
		:in_EMPLOYMENT_GRP_CDE,
		:in_MARITAL_STA,
		:in_SEX_CDE,
		:in_DOB,
		:in_EMPLR_NAME,
		:in_EMPLR_OCCUP_CDE,
		:in_EMPLOYMENT_NARR,
		:in_EMPLOYMENT_DTE,
		:in_EMPLOYMENT_STA_CDE,
		:in_EMPL_CLS_EMPL,
		:in_EMPL_CLS_SELF,
		:in_EMPL_CLS_HOUSEWIFE,
		:in_EMPL_CLS_STUDENT,
		:in_EMPL_CLS_RETIRED,
		:in_EMPL_CLS_UNEMPLOYED,
		:in_EMPL_TYPE_PERM,
		:in_EMPL_TYPE_PART_TIME,
		:in_EMPL_TYPE_TEMP,
		:in_EMPL_TYPE_PENSION,
		:in_EMPL_TYPE_FULL_TIME,
		:in_SALARY_EFF_DTE,
		:in_INC_AMT,
		:in_INC_REF_CRNCY_AMT,
		:in_INC_RANGE,
		:in_PAY_DIR,
		:in_NET_MONTHLY_PAY,
		:in_NET_MONTHLY_REF_CRNCY_PAY,
		:in_PAY_FREQ,
		:in_FAMILY_TOTAL_NO,
		:in_FAMILY_FROM_DTE,
		:in_FAMILY_TO_DTE,
		:in_HOUSE_STA_CDE,
		:in_HOUSE_VALUE,
		:in_HOUSE_REF_CRNCY_VALUE,
		:in_HOUSE_VALUE_DTE,
		:in_DECEASED_FLG,
		:in_PERSONAL_RSI,
		:in_PART_TIME_HOURS,
		:in_STUDENT_CAT_CDE,
		:in_PRIM_SCH_NAME,
		:in_PRIM_END_DTE,
		:in_SECNDRY_SCH_NAME,
		:in_SECNDRY_END_DTE,
		:in_TRD_LEV_CDE,
		:in_CRSE_TYP_CDE,
		:in_FAC_CDE,
		:in_CRSE_TITLE,
		:in_CRSE_START_DTE,
		:in_CRSE_END_DTE,
		:in_AMEND_RSN_CDE,
		:in_LAST_STAFF_CDE,
		:in_LAST_UPD_STUDENT_DTE,
		:in_LAST_UPD_STUDENT_TIME,
		:in_WH_OPEN_DTE,
		:in_MONTHLY_NET_INCOME_VERFD_AMT,
		:in_MONTHLY_NET_INCOME_VERFD_DTE,
		:in_MONTHLY_NET_INCOME_VERFD_TYP,
		:in_PROFESSION_TYPE_CDE,
		:in_LOAD_LAST_ACTION,
		:in_LOAD_DTE,
		:in_LOAD_TIME
      );
      .IMPORT INFILE ../dane_testowe/CUSTOMER_PERSONAL_DETAIL2_DATA_FILE.dat
      FORMAT VARTEXT ''
      LAYOUT Data
      APPLY DataLabel;  
   .END MLOAD;  
LOGOFF;

