.LOGTABLE vmtest.logtable;

.logon 127.0.0.1/dbc, dbc;

   .BEGIN MLOAD TABLES vmtest.CUSTOMER_ACCOUNT_REL_PERIODIC;
      .LAYOUT Data;
	    .FIELD in_WH_CUST_NO  * VARCHAR(20);
		.FIELD in_WH_ACC_NO  * VARCHAR(20);
		.FIELD in_SRCE_CUST_NO * VARCHAR(19) ;
		.FIELD in_SRCE_INST  * VARCHAR(20) ;
		.FIELD in_ACC_NO * VARCHAR(16) ;
		.FIELD in_REL_TYP_CDE * VARCHAR(2) ;
		.FIELD in_SRCE_REL_TYP_CDE * VARCHAR(3) ;
		.FIELD in_LAST_VERIFICATION_DTE  * VARCHAR(20) ;
		.FIELD in_LAST_MAINTAINED_DTE  * VARCHAR(20) ;
		.FIELD in_PERIOD_DTE  * VARCHAR(20) ;
		.FIELD in_LOAD_DTE  * VARCHAR(20) ;
		.FIELD in_LOAD_TIME  * VARCHAR(20) ;

      .DML LABEL DataLabel;
      INSERT INTO vmtest.CUSTOMER_ACCOUNT_REL_PERIODIC
      VALUES (
        :in_WH_CUST_NO,
		:in_WH_ACC_NO ,
		:in_SRCE_CUST_NO,
		:in_SRCE_INST ,
		:in_ACC_NO,
		:in_REL_TYP_CDE,
		:in_SRCE_REL_TYP_CDE,
		:in_LAST_VERIFICATION_DTE ,
		:in_LAST_MAINTAINED_DTE ,
		:in_PERIOD_DTE ,
		:in_LOAD_DTE ,
		:in_LOAD_TIME
      );
      .IMPORT INFILE ../dane_testowe/CUSTOMER_ACCOUNT_REL_PERIODIC_DATA_FILE.dat
      FORMAT VARTEXT ''
      LAYOUT Data
      APPLY DataLabel;  
   .END MLOAD;  
LOGOFF;

