.LOGTABLE vmtest.logtable;

.logon 127.0.0.1/dbc, dbc;

   .BEGIN MLOAD TABLES vmtest.PRODUCT_BZWBK;
      .LAYOUT Data;
		.FIELD in_PROD_CDE * VARCHAR(20);
		.FIELD in_SRCE_SYS * VARCHAR(20);
		.FIELD in_SRCE_PROD_CDE * VARCHAR(20) ;
		.FIELD in_SRCE_PROD_ID * VARCHAR(5) ;
		.FIELD in_PROD_NAME * VARCHAR(100) ;
		.FIELD in_PROD_STA_CDE * VARCHAR(4) ;
		.FIELD in_PROD_CAT_DESCR * VARCHAR(50) ;
		.FIELD in_PROD_SUMM_DESCR * VARCHAR(50) ;
		.FIELD in_PROD_GRP_DESCR * VARCHAR(50) ;
		.FIELD in_PROD_DTL_GRP_DESCR * VARCHAR(50) ;
		.FIELD in_PROD_DTL_DESCR * VARCHAR(50) ;
		.FIELD in_INTEREST_PLAN_NO * VARCHAR(6) ;
		.FIELD in_CHARGE_PLAN_NO * VARCHAR(6) ;
		.FIELD in_ISO_CRNCY_CDE * VARCHAR(3) ;
		.FIELD in_PURPOSE_CDE * VARCHAR(5) ;
		.FIELD in_MATURITY_GRP_CDE * VARCHAR(3) ;
		.FIELD in_START_DTE * VARCHAR(20) ;
		.FIELD in_END_DTE * VARCHAR(20) ;
		.FIELD in_LOAD_LAST_ACTION * VARCHAR(1) ;
		.FIELD in_LOAD_DTE * VARCHAR(20) ;
		.FIELD in_LOAD_TIME * VARCHAR(20) ;

      .DML LABEL DataLabel;
      INSERT INTO vmtest.PRODUCT_BZWBK
      VALUES (
		:in_PROD_CDE,
		:in_SRCE_SYS,
		:in_SRCE_PROD_CDE,
		:in_SRCE_PROD_ID,
		:in_PROD_NAME,
		:in_PROD_STA_CDE,
		:in_PROD_CAT_DESCR,
		:in_PROD_SUMM_DESCR,
		:in_PROD_GRP_DESCR,
		:in_PROD_DTL_GRP_DESCR,
		:in_PROD_DTL_DESCR,
		:in_INTEREST_PLAN_NO,
		:in_CHARGE_PLAN_NO,
		:in_ISO_CRNCY_CDE,
		:in_PURPOSE_CDE,
		:in_MATURITY_GRP_CDE,
		:in_START_DTE,
		:in_END_DTE,
		:in_LOAD_LAST_ACTION,
		:in_LOAD_DTE,
		:in_LOAD_TIME
      );
      .IMPORT INFILE ../dane_testowe/PRODUCT_BZWBK_DATA_FILE.dat
      FORMAT VARTEXT ''
      LAYOUT Data
      APPLY DataLabel;  
   .END MLOAD;  
LOGOFF;

