.LOGTABLE vmtest.logtable;

.logon 127.0.0.1/dbc, dbc;

   .BEGIN MLOAD TABLES vmtest.TRANSACTION_DETAIL;
      .LAYOUT Data;
		.FIELD in_TRANS_TYPE  * VARCHAR(20) ;
		.FIELD in_WH_ACC_NO  * VARCHAR(20) ;
		.FIELD in_WH_CHNL_ID  * VARCHAR(20) ;
		.FIELD in_POSTED_CRNCY_CDE  * VARCHAR(3) ;
		.FIELD in_POSTED_AMT  * VARCHAR(20) ;
		.FIELD in_POSTED_REF_CRNCY_AMT  * VARCHAR(20) ;
		.FIELD in_POSTED_DTE  * VARCHAR(20) ;
		.FIELD in_TRANS_DTE  * VARCHAR(20) ;
		.FIELD in_TRANS_TIME  * VARCHAR(20) ;
		.FIELD in_CLEAR_REJ  * VARCHAR(1) ;
		.FIELD in_SRCE_NSC  * VARCHAR(20) ;
		.FIELD in_SRCE_SYS  * VARCHAR(20) ;
		.FIELD in_POSTED_ACC_NO  * VARCHAR(16) ;
		.FIELD in_SEQUENCE_NO  * VARCHAR(20) ;
		.FIELD in_CHNL_TYP  * VARCHAR(20) ;
		.FIELD in_USER_ID  * VARCHAR(10) ;
		.FIELD in_BATCH_NO  * VARCHAR(50) ;
		.FIELD in_SRCE_SEQUENCE_NO  * VARCHAR(20) ;
		.FIELD in_TRANS_TITLE_TXT  * VARCHAR(255) ;
		.FIELD in_TRANS_CUST_NAME  * VARCHAR(80) ;
		.FIELD in_OTH_CUST_NAME  * VARCHAR(80) ;
		.FIELD in_OTH_CUST_BANK_CDE  * VARCHAR(8) ;
		.FIELD in_OTH_CUST_ACC_NO  * VARCHAR(30) ;
		.FIELD in_TRANS_REVERSAL_CDE  * VARCHAR(4) ;
		.FIELD in_TRANS_TYP_GRP_CDE  * VARCHAR(6) ;
		.FIELD in_TRANS_NARR_STAFF_TXT  * VARCHAR(10) ;
		.FIELD in_TRANS_SRCE_BRANCH_CDE  * VARCHAR(5) ;
		.FIELD in_OWNER_ACCOUNT_TRANSFER_IND  * VARCHAR(1) ;
		.FIELD in_SALARY_IND  * VARCHAR(1) ;
		.FIELD in_SRCE_INST  * VARCHAR(20) ;
		.FIELD in_LOAD_DTE  * VARCHAR(20) ;
		.FIELD in_LOAD_TIME  * VARCHAR(20) ;

      .DML LABEL DataLabel;
      INSERT INTO vmtest.TRANSACTION_DETAIL
      VALUES (
		:in_TRANS_TYPE,
		:in_WH_ACC_NO,
		:in_WH_CHNL_ID,
		:in_POSTED_CRNCY_CDE,
		:in_POSTED_AMT,
		:in_POSTED_REF_CRNCY_AMT,
		:in_POSTED_DTE,
		:in_TRANS_DTE,
		:in_TRANS_TIME,
		:in_CLEAR_REJ,
		:in_SRCE_NSC,
		:in_SRCE_SYS,
		:in_POSTED_ACC_NO,
		:in_SEQUENCE_NO,
		:in_CHNL_TYP,
		:in_USER_ID,
		:in_BATCH_NO,
		:in_SRCE_SEQUENCE_NO,
		:in_TRANS_TITLE_TXT,
		:in_TRANS_CUST_NAME,
		:in_OTH_CUST_NAME,
		:in_OTH_CUST_BANK_CDE,
		:in_OTH_CUST_ACC_NO,
		:in_TRANS_REVERSAL_CDE,
		:in_TRANS_TYP_GRP_CDE,
		:in_TRANS_NARR_STAFF_TXT,
		:in_TRANS_SRCE_BRANCH_CDE,
		:in_OWNER_ACCOUNT_TRANSFER_IND,
		:in_SALARY_IND,
		:in_SRCE_INST,
		:in_LOAD_DTE,
		:in_LOAD_TIME
      );
      .IMPORT INFILE ../dane_testowe/TRANSACTION_DETAIL.dat
      FORMAT VARTEXT ''
      LAYOUT Data
      APPLY DataLabel;  
   .END MLOAD;  
LOGOFF;

