.LOGTABLE vmtest.logtable;

.logon 127.0.0.1/dbc, dbc;

   .BEGIN MLOAD TABLES vmtest.TRANSACTION_CARD_DETAIL_BZWBK;
      .LAYOUT Data;
		.FIELD in_WH_CARD_NO * VARCHAR(20) ;
		.FIELD in_TLOG_ID * VARCHAR(20);
		.FIELD in_CARD_NO * VARCHAR(19) ;
		.FIELD in_ACC_NO * VARCHAR(16) ;
		.FIELD in_TRACE_AUDIT_NO * VARCHAR(20);
		.FIELD in_REVERSAL_TRACE_AUDIT_NO * VARCHAR(20) ;
		.FIELD in_REFERENCE_ID * VARCHAR(12) ;
		.FIELD in_CARD_EXPIRY_CDE * VARCHAR(4) ;
		.FIELD in_SERVICE_CDE * VARCHAR(40) ;
		.FIELD in_ACCEPTOR_ID * VARCHAR(15) ;
		.FIELD in_ACCEPTOR_TXT * VARCHAR(70) ;
		.FIELD in_ACCEPTOR_TYP * VARCHAR(20) ;
		.FIELD in_TERMINAL_ID * VARCHAR(16) ;
		.FIELD in_DATA_INPUT_CAPABILITY_CDE * VARCHAR(1) ;
		.FIELD in_DATA_INPUT_MODE_CDE * VARCHAR(1) ;
		.FIELD in_HOLDER_AUTH_CAPABILITY_TYP * VARCHAR(1) ;
		.FIELD in_HOLDER_AUTH_METHOD_TYP * VARCHAR(1) ;
		.FIELD in_HOLDER_PRESENT_CDE * VARCHAR(1) ;
		.FIELD in_HOLDER_AUTH_ENTITY_ID * VARCHAR(1) ;
		.FIELD in_CARD_PRESENT_CDE * VARCHAR(1) ;
		.FIELD in_ACQUIRER_ID * VARCHAR(11) ;
		.FIELD in_ACQUIRER_ISO_CNTRY_CDE * VARCHAR(3) ;
		.FIELD in_TRANS_DTE * VARCHAR(20) ;
		.FIELD in_TRANS_TIME * VARCHAR(20) ;
		.FIELD in_MESSAGE_CLASS_TYP * VARCHAR(1) ;
		.FIELD in_MESSAGE_PURPOSE_CDE * VARCHAR(20) ;
		.FIELD in_MESSAGE_FUNCTION_TYP * VARCHAR(1) ;
		.FIELD in_MESSAGE_REVERSAL_TYP * VARCHAR(1) ;
		.FIELD in_TRANS_INITIATOR_CDE * VARCHAR(1) ;
		.FIELD in_TRANS_REVERSAL_CDE * VARCHAR(1) ;
		.FIELD in_TRANS_TYPE * VARCHAR(20) ;
		.FIELD in_TRANS_STA_CDE * VARCHAR(20) ;
		.FIELD in_TRANS_RESPONSE_SRCE_TYP * VARCHAR(2) ;
		.FIELD in_TRANS_REJECTION_CDE * VARCHAR(20) ;
		.FIELD in_TRANS_CRNCY_CDE * VARCHAR(3) ;
		.FIELD in_POSTED_AMT * VARCHAR(20);
		.FIELD in_SETTLEMENT_AMT * VARCHAR(20);
		.FIELD in_SETTLEMENT_CRNCY_CDE * VARCHAR(3) ;
		.FIELD in_POSTED_ACC_NO * VARCHAR(28) ;
		.FIELD in_TRAN_ACTION_CDE * VARCHAR(1) ;
		.FIELD in_TRAN_ACTION_REASON_CDE * VARCHAR(20) ;
		.FIELD in_TRAN_RESPONSE_CDE * VARCHAR(20) ;
		.FIELD in_POSTED_DTE * VARCHAR(20) ;
		.FIELD in_ACQUIRER_INST_CDE * VARCHAR(8) ;
		.FIELD in_CARD_ISSUER_CDE * VARCHAR(8) ;
		.FIELD in_RECONCILIATION_CDE * VARCHAR(3) ;
		.FIELD in_CARD_CRNCY_CDE * VARCHAR(3) ;
		.FIELD in_POSTED_REF_CRNCY_AMT * VARCHAR(20);
		.FIELD in_CARD_PROD_TXN_CDE * VARCHAR(7) ;
		.FIELD in_SRCE_INST * VARCHAR(20) ;
		.FIELD in_SRCE_SYS * VARCHAR(20) ;
		.FIELD in_POSTED_LCRNCY_AMT * VARCHAR(20);
		.FIELD in_POSTED_CASH_BACK_AMT * VARCHAR(20);
		.FIELD in_TRAN_RECON_AUTH_CDE * VARCHAR(9) ;
		.FIELD in_LOAD_DTE * VARCHAR(20) ;
		.FIELD in_LOAD_TIME * VARCHAR(20) ;

      .DML LABEL DataLabel;
      INSERT INTO vmtest.TRANSACTION_CARD_DETAIL_BZWBK
      VALUES (
		:in_WH_CARD_NO,
		:in_TLOG_ID,
		:in_CARD_NO,
		:in_ACC_NO,
		:in_TRACE_AUDIT_NO,
		:in_REVERSAL_TRACE_AUDIT_NO,
		:in_REFERENCE_ID,
		:in_CARD_EXPIRY_CDE,
		:in_SERVICE_CDE,
		:in_ACCEPTOR_ID,
		:in_ACCEPTOR_TXT,
		:in_ACCEPTOR_TYP,
		:in_TERMINAL_ID,
		:in_DATA_INPUT_CAPABILITY_CDE,
		:in_DATA_INPUT_MODE_CDE,
		:in_HOLDER_AUTH_CAPABILITY_TYP,
		:in_HOLDER_AUTH_METHOD_TYP,
		:in_HOLDER_PRESENT_CDE,
		:in_HOLDER_AUTH_ENTITY_ID,
		:in_CARD_PRESENT_CDE,
		:in_ACQUIRER_ID,
		:in_ACQUIRER_ISO_CNTRY_CDE,
		:in_TRANS_DTE,
		:in_TRANS_TIME,
		:in_MESSAGE_CLASS_TYP,
		:in_MESSAGE_PURPOSE_CDE,
		:in_MESSAGE_FUNCTION_TYP,
		:in_MESSAGE_REVERSAL_TYP,
		:in_TRANS_INITIATOR_CDE,
		:in_TRANS_REVERSAL_CDE,
		:in_TRANS_TYPE,
		:in_TRANS_STA_CDE,
		:in_TRANS_RESPONSE_SRCE_TYP,
		:in_TRANS_REJECTION_CDE,
		:in_TRANS_CRNCY_CDE,
		:in_POSTED_AMT,
		:in_SETTLEMENT_AMT,
		:in_SETTLEMENT_CRNCY_CDE,
		:in_POSTED_ACC_NO,
		:in_TRAN_ACTION_CDE,
		:in_TRAN_ACTION_REASON_CDE,
		:in_TRAN_RESPONSE_CDE,
		:in_POSTED_DTE,
		:in_ACQUIRER_INST_CDE,
		:in_CARD_ISSUER_CDE,
		:in_RECONCILIATION_CDE,
		:in_CARD_CRNCY_CDE,
		:in_POSTED_REF_CRNCY_AMT,
		:in_CARD_PROD_TXN_CDE,
		:in_SRCE_INST,
		:in_SRCE_SYS,
		:in_POSTED_LCRNCY_AMT,
		:in_POSTED_CASH_BACK_AMT,
		:in_TRAN_RECON_AUTH_CDE,
		:in_LOAD_DTE,
		:in_LOAD_TIME
      );
      .IMPORT INFILE ../dane_testowe/TRANSACTION_CARD_DETAIL_BZWBK_DATA_FILE.dat
      FORMAT VARTEXT ''
      LAYOUT Data
      APPLY DataLabel;  
   .END MLOAD;  
LOGOFF;

